// mvp-cards.ts
// FIXED — 変更禁止
import { Card } from "./mvp-types";

export const CARDS: Card[] = [
  {
    id: "b_value_one_sentence",
    channel: "B",
    title: "大事なことを一つ書く",
    why: "大事なものが言葉になると、気持ちが定まります。",
    steps: ["紙やメモに「私は◯◯を大事にする」と一文で書く"],
    duration_sec: 120,
  },
  {
    id: "b_courage_phrase",
    channel: "B",
    title: "自分にかける言葉を決める",
    why: "短い言葉は、迷った時の支えになります。",
    steps: [
      "「私は◯◯する」と短い言葉を一つ決める",
      "画面の待受やメモに残す",
    ],
    duration_sec: 180,
  },
  {
    id: "b_meaning_question",
    channel: "B",
    title: "意味の問いを一つ立てる",
    why: "問いがあると、心が散らばりにくくなります。",
    steps: [
      "「この出来事が教えていることは何？」と書く",
      "今の答えを一行だけ書く",
    ],
    duration_sec: 180,
  },
  {
    id: "a_emotion_three_words",
    channel: "A",
    title: "感情を3語にする",
    why: "言葉にすると、感情の波が少し落ち着きます。",
    steps: ["今の気持ちを3つの単語で書く（例：不安／悔しい／さみしい）"],
    duration_sec: 120,
  },
  {
    id: "a_voice_release",
    channel: "A",
    title: "声と表情を動かす",
    why: "表情や声が動くと、内側も動き出します。",
    steps: ["口を大きく開けて「あー」と5秒×3回", "肩の力を抜く"],
    duration_sec: 120,
  },
  {
    id: "a_music_one_piece",
    channel: "A",
    title: "1曲だけ鳴らす・聴く",
    why: "音は気分の調律に役立ちます。",
    steps: [
      "いま必要な気分になる1曲を選ぶ",
      "1曲だけ鳴らす／聴く",
    ],
    duration_sec: 180,
  },
  {
    id: "s_send_one_line",
    channel: "S",
    title: "一言だけ送る",
    why: "つながりは安心感を作ります。",
    steps: [
      "信頼できる相手を1人選ぶ",
      "「今ちょっと緊張してる」など一言だけ送る",
    ],
    duration_sec: 120,
  },
  {
    id: "s_support_list",
    channel: "S",
    title: "頼れる先を3つ書く",
    why: "頼れる可能性が見えると、余裕が増えます。",
    steps: ["名前でも組織でもOKで3つ書く（家族／友人／窓口など）"],
    duration_sec: 180,
  },
  {
    id: "s_photo_gaze",
    channel: "S",
    title: "写真を見て深呼吸",
    why: "大事な存在を思い出すと、心が落ち着きます。",
    steps: ["ペットや家族などの写真を30秒見る", "ゆっくり息を吐く"],
    duration_sec: 120,
  },
  {
    id: "i_safe_scene",
    channel: "I",
    title: "安心できる場面を思い浮かべる",
    why: "頭の中の風景が、今の感覚に影響します。",
    steps: [
      "安心できる場所を一つ思い浮かべる",
      "色・音・匂いを1つずつ足す",
    ],
    duration_sec: 180,
  },
  {
    id: "i_story_line",
    channel: "I",
    title: "物語の一文をつくる",
    why: "物語にすると、出来事が少し扱いやすくなります。",
    steps: ["「これは◯◯な旅のはじまりだ」と一文で書く"],
    duration_sec: 120,
  },
  {
    id: "i_future_postcard",
    channel: "I",
    title: "未来の自分から一言",
    why: "少し先の視点が入ると、今が軽くなります。",
    steps: ["1週間後の自分を想像する", "いまの自分へ一言だけ書く"],
    duration_sec: 180,
  },
  {
    id: "c_three_tasks",
    channel: "C",
    title: "やることを3つに絞る",
    why: "数が減ると、頭が静かになります。",
    steps: ["今やることを3つだけ書く", "一番上だけ丸をつける"],
    duration_sec: 120,
  },
  {
    id: "c_next_small_step",
    channel: "C",
    title: "次の一歩を決める",
    why: "小さな一歩が、落ち着きを取り戻します。",
    steps: [
      "5分でできる行動を1つ決める",
      "それを今やる／開始時間を決める",
    ],
    duration_sec: 180,
  },
  {
    id: "c_fact_vs_worry",
    channel: "C",
    title: "事実と心配を分ける",
    why: "混ざると増えるので、分けると整います。",
    steps: [
      "紙を2列にする（事実／心配）",
      "それぞれ1〜3行ずつ書く",
    ],
    duration_sec: 180,
  },
  {
    id: "ph_long_exhale",
    channel: "Ph",
    title: "息を長く吐く",
    why: "吐く息が長いと、身体が落ち着きやすくなります。",
    steps: ["鼻から4秒吸う", "口から6秒吐く", "これを10回"],
    duration_sec: 180,
  },
  {
    id: "ph_feet_contact",
    channel: "Ph",
    title: "足の裏を感じる",
    why: "身体感覚に戻ると、頭が静かになります。",
    steps: [
      "足の裏の感覚に30秒注意を向ける",
      "床を軽く踏む×10回",
    ],
    duration_sec: 120,
  },
  {
    id: "ph_sip_water",
    channel: "Ph",
    title: "水をゆっくり飲む",
    why: "ゆっくりした動きは、身体に安心を伝えます。",
    steps: ["一口ふくむ", "2秒止めてから飲み込む", "これを5回"],
    duration_sec: 120,
  },
];
